name: ProductListSlot
description: This slot is used to capture a list of products.
examples:
- yogurt, beans, tomatoes
- pasta, tomatoes
- cheese, milk
- bananas
- apples, oranges, grapes
- carrots, broccoli, spinach
- ketchup, mustard, mayonnaise
- chicken, beef, tofu
