name: ProductQuantitySlot
description: This slot is used to capture the quantity of a product.
examples:
- 3 gallons
- 1 pound
- 2 boxes
- 5 liters
- 10 pieces
- 4 packets
- 6 bottles
- 8 cans
- 7 items
- 12 units